/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jfjoibiigmkazyrqgpfl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmam9pYmlpZ21rYXp5cnFncGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NjkyMDksImV4cCI6MjA4OTE0NTIwOX0.AThnOKetMWshTtvOH8MqmHH--hO2QylWiDeWX_FhRuo"